### ISSUE TITLE
launching kit app

### ISSUE THREAD

**Issue by Alisiam2020** [nv-tlabs/DiffusionTexturePainting#1]
When trying to launch the kit app, using bash launch_app.sh, I get a permission denied message for: `DiffusionTexturePainting/kit_app/_build/linux-x86_64/release/kit/kit: Permission denied`
Changing permission did not work. Should I have Omniverse kit app installed before running the code?

**Comment by anita-hu** [comment]
No, you don't need to. When you build the app, it will download everything that is needed. 
I have not encountered this myself. If you can send the full log, I can try to help

**Comment by RuihanGao** [comment]
> When trying to launch the kit app, using bash launch_app.sh, I get a permission denied message for: `DiffusionTexturePainting/kit_app/_build/linux-x86_64/release/kit/kit: Permission denied` Changing permission did not work. Should I have Omniverse kit app installed before running the code?

Did you figure it out? I encountered the same issue when trying to launch the kit app.

```
(base) ruihang@capybara:/data/ruihan/projects/DiffusionTexturePainting$ bash launch_app.sh
./kit_app/_build/linux-x86_64/release/texture_painter_app.sh: line 4: /data/ruihan/projects/DiffusionTexturePainting/kit_app/_build/linux-x86_64/release/kit/kit: Permission denied
```

**Comment by anita-hu** [comment]
Please check results of chmod. If permissions set correctly, it should show
DiffusionTexturePainting/kit_app/_build/linux-x86_64/release/kit$ ls -l kit
-rwxr-xr-x 
Or make sure you checked "Allow executing file as program" for kit properties

<img width="444" height="435" alt="Image" src="https://github.com/user-attachments/assets/92360b15-7355-469f-a12b-c0080eb3c336" />

**Comment by anita-hu** [comment]
If permissions is set correctly then this command should work
./DiffusionTexturePainting/kit_app/_build/linux-x86_64/release/kit/kit --help
