### ISSUE TITLE
can't clone lfs files

### ISSUE THREAD

**Issue by onanimationadmin** [nv-tlabs/DiffusionTexturePainting#3]
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/nv-tlabs/DiffusionTexturePainting.git/info/lfs'

**Comment by anita-hu** [comment]
Sorry for the delay. 
I created a github support ticket to purge removed files from lfs storage. Will close ticket when completed

**Comment by anita-hu** [comment]
In the meantime, you can download the files [here](https://drive.google.com/file/d/14c8XHuX89fUhmhvRaozZHbKJK2lQB-5L/view?usp=sharing) and unzip the files to `DiffusionTexturePainting/kit_app/source/extensions/aitoybox.texture_painter/data`

**Comment by anita-hu** [comment]
I removed the lfs files and uploaded as regular git files. It is fixed now
